#!/usr/bin/env python3
"""
Export uncoded committee and government bills with Knesset website links.

Filters for K10-24 excluding K21-22, where MAJORIL is NA/empty.
Produces two Excel files (one per bill type) for RA distribution.

Usage:
    python export_uncoded_committee_gov_bills.py
    python export_uncoded_committee_gov_bills.py --output-dir data/gap_analysis
"""

import argparse
from pathlib import Path

import pandas as pd

KNESSET_BILL_URL = (
    "https://main.knesset.gov.il/Activity/Legislation/Laws/Pages/"
    "LawBill.aspx?t=lawsuggestionssearch&lawitemid={bill_id}"
)

PROJECT_ROOT = Path(__file__).resolve().parent

# Input CSVs (generated by import_filtered_coding.py)
COMMITTEE_INPUT = PROJECT_ROOT / "filtered_Bill_ועדה_with_coding.csv"
GOV_INPUT = PROJECT_ROOT / "filtered_Bill_ממשלתית_with_coding.csv"

# Knessets to include and exclude
KNESSET_MIN = 10
KNESSET_MAX = 24
EXCLUDE_KNESSETS = {21, 22}


def filter_uncoded(df: pd.DataFrame) -> pd.DataFrame:
    """Filter to uncoded rows in target Knesset range."""
    # Uncoded = MAJORIL is NA or empty string
    uncoded = df[
        df["MAJORIL"].isna()
        | (df["MAJORIL"].astype(str).str.strip().isin(["NA", ""]))
    ].copy()

    # Filter Knesset range
    uncoded = uncoded[
        (uncoded["KnessetNum"] >= KNESSET_MIN)
        & (uncoded["KnessetNum"] <= KNESSET_MAX)
        & ~uncoded["KnessetNum"].isin(EXCLUDE_KNESSETS)
    ]

    return uncoded


def add_links_and_format(df: pd.DataFrame, bill_type: str) -> pd.DataFrame:
    """Add Knesset website links and format output columns."""
    df["KnessetLink"] = df["ItemID"].apply(
        lambda bid: KNESSET_BILL_URL.format(bill_id=int(bid))
    )

    # Select output columns (committee/gov bills may not have InitiatorName/FactionName)
    output_cols = ["ItemID", "KnessetNum", "ItemName", "Status", "KnessetLink"]

    # Add InitiatorName and FactionName if they have any non-null values
    if "InitiatorName" in df.columns and df["InitiatorName"].notna().any():
        output_cols.insert(4, "InitiatorName")
    if "FactionName" in df.columns and df["FactionName"].notna().any():
        output_cols.insert(5, "FactionName")

    output_df = df[output_cols].copy()
    output_df = output_df.rename(columns={"ItemID": "BillID"})
    output_df = output_df.sort_values(["KnessetNum", "BillID"])

    return output_df


def export_bill_type(
    input_path: Path, output_path: Path, bill_type: str
) -> int:
    """Export uncoded bills of a given type. Returns count exported."""
    if not input_path.exists():
        print(f"  Input file not found: {input_path.name}")
        return 0

    df = pd.read_csv(input_path, encoding="utf-8-sig")
    print(f"  Read {len(df)} total {bill_type} bills from {input_path.name}")

    uncoded = filter_uncoded(df)
    if uncoded.empty:
        print(f"  No uncoded {bill_type} bills in K{KNESSET_MIN}-{KNESSET_MAX}")
        return 0

    output_df = add_links_and_format(uncoded, bill_type)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_df.to_excel(output_path, index=False, engine="openpyxl")
    print(f"  Exported {len(output_df)} uncoded {bill_type} bills to {output_path.name}")

    # Summary by Knesset
    for kn, group in output_df.groupby("KnessetNum"):
        print(f"    K{kn}: {len(group)} bills")

    return len(output_df)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export uncoded committee and government bills with Knesset links"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "data" / "gap_analysis",
    )
    args = parser.parse_args()

    print(
        f"Exporting uncoded bills for K{KNESSET_MIN}-K{KNESSET_MAX} "
        f"(excluding K{', K'.join(str(k) for k in sorted(EXCLUDE_KNESSETS))})\n"
    )

    total = 0

    # Committee bills
    print("Committee bills (הצעות חוק ועדה):")
    total += export_bill_type(
        COMMITTEE_INPUT,
        args.output_dir / "uncoded_committee_bills_with_links.xlsx",
        "committee",
    )
    print()

    # Government bills
    print("Government bills (הצעות חוק ממשלתיות):")
    total += export_bill_type(
        GOV_INPUT,
        args.output_dir / "uncoded_government_bills_with_links.xlsx",
        "government",
    )

    print(f"\nTotal: {total} uncoded bills exported")
    print("Share the Excel files with the research assistant for coding.")


if __name__ == "__main__":
    main()
